"""empty message

Revision ID: 097f91a46260
Revises: db4e36741075
Create Date: 2024-03-20 16:57:28.997118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097f91a46260'
down_revision = 'db4e36741075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.String(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')

    # ### end Alembic commands ###
