"""empty message

Revision ID: 371476d28b9e
Revises: c71772bfb68d
Create Date: 2024-03-21 11:36:28.131919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371476d28b9e'
down_revision = 'c71772bfb68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateOfBirth', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(), nullable=True))
        batch_op.drop_column('patient_or_doctor')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('reason_for_therapy')

    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dateOfBirth', sa.String(), nullable=True))
        batch_op.drop_column('patient_or_doctor')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('patient_or_doctor', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('dateOfBirth')
        batch_op.drop_column('phoneNumber')

    with op.batch_alter_table('Patients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_for_therapy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('patient_or_doctor', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('dateOfBirth')

    # ### end Alembic commands ###
