"""empty message

Revision ID: 424a9781abde
Revises: 6643084d113c
Create Date: 2024-03-20 13:31:42.560868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424a9781abde'
down_revision = '6643084d113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('patient_or_doctor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.drop_column('patient_or_doctor')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
