"""empty message

Revision ID: 695087a571b1
Revises: 963c7feb20ac
Create Date: 2024-03-27 12:21:48.651196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695087a571b1'
down_revision = '963c7feb20ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.String(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')

    # ### end Alembic commands ###
