"""empty message

Revision ID: b72631fbdf9b
Revises: e8e014a8b519
Create Date: 2024-03-18 16:50:06.115335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72631fbdf9b'
down_revision = 'e8e014a8b519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_or_doctor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients_table', schema=None) as batch_op:
        batch_op.drop_column('patient_or_doctor')

    # ### end Alembic commands ###
