"""empty message

Revision ID: db4e36741075
Revises: 424a9781abde
Create Date: 2024-03-20 16:16:40.556491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4e36741075'
down_revision = '424a9781abde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_id_num', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Therapists_table', schema=None) as batch_op:
        batch_op.drop_column('medical_id_num')

    with op.batch_alter_table('Appointments_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
